### ISSUE TITLE
Dataform CLI - gettablemetadata - TypeError: Expected a string, got object

### ISSUE THREAD

**Issue by adityaschauhan** [dataform-co/dataform#1388] opened 2022-10-27 08:53 UTC
Error can be reproduced as mentioned in [issue 1358](https://github.com/dataform-co/dataform/issues/1358).

While running `dataform gettablemetadata <warehouse> <schema> <table> `  I face the below error.

```
Dataform encountered an error: Expected a string, got object
TypeError: Expected a string, got object
    at module.exports (/usr/local/lib/node_modules/@dataform/cli/node_modules/untildify/index.js:8:9)
    at actuallyResolve (/usr/local/lib/node_modules/@dataform/cli/bundle.js:26973:52)
    at Object.processFn (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27945:78)
    at Object.handler (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27076:44)
```

**Comment by Ekrekr** [comment] 2023-02-10 18:42
Closing as I think this is a duplicate of https://github.com/dataform-co/dataform/issues/1358 - LMK if otherwise 🙂

**Closed by Ekrekr** 2023-02-10 18:42 UTC
