### ISSUE TITLE
Attempting to re-create datasets in Bigquery in another region leads to confusing errors

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#99] opened 2019-03-06 16:01 UTC
In BigQuery, when starting a run, the first thing we do is attempt to create a dataset in the default location provided when connecting to a warehouse. If a dataset with this name already exists but in another region, the call will silently fail and not create the dataset.

Any attempts to create tables or views in that dataset will subsequently fail with an error message like:
`Dataset [my_dataset] does not exist in location EU`

When we attempt to create the dataset, and it already exists in a region different from the one specified in the data warehouse connection profile - we should throw an appropriate error in prepareDataset: https://github.com/dataform-co/dataform/blob/master/api/dbadapters/bigquery.ts#L120

Something like `Cannot create dataset my_dataset in location EU as it already exists in location US/another location. Change your default dataset location or delete the exist dataset.`

**Comment by mshakhomirov** [comment] 2021-08-05 17:21
Indeed. I have a Firebase project in US region which extracts data into BigQuery daily (same US location). My server events historically go to europe-west-2 region tables. Attempt to run any query on tables in US region in my dataform configured for europe-west-2 will result in: Error: Not found: Dataset my-data:analytics_152444 was not found in location europe-west2.

**Comment by Ekrekr** [comment] 2024-03-26 11:56
We no longer silently fail with this, we loudly fail with the error that BigQuery gives us; `bigquery error: Not found: Dataset cloud-dataform-testing:dataform_core_testing was not found in location EU`:

![image](https://github.com/dataform-co/dataform/assets/13434377/356e65ee-58cc-4c9c-9d19-a59bf3f765b5)

The error message isn't great, but I don't think we should change this:
* We're returning the literal error that BigQuery gives us when attempting to recreate a schema - it is their API error which should be changed to make it more clear.
* Attempting to hack around the returned error message will likely create other errors, where we say it's due to a location error when it's not.
* It's not too difficult to deduce why schema creation failed in these situations.

So closing this now as works as intended.

**Closed by Ekrekr** 2024-03-26 11:56 UTC
Labels: UX Papercut
