### ISSUE TITLE
Issue with textDocument/definition in Dataform Extension for VS Code (cmd+click feature)

### ISSUE THREAD

**Issue by Mallington** [dataform-co/dataform#1556] opened 2023-10-25 00:25 UTC
While using the Dataform extension for Visual Studio Code, I encountered an error when using the cmd + click shortcut on ref() functions.

### Expected Functionality:
It should go to the file that it references.

### Actual Functionality:
This is the error which occurs:
```
[Error - 23:54:48] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read properties of undefined (reading 'split')
  Code: -32603
```
### Extension Version:
v0.0.11

### Vscode Info:
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z (2 wks ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by Ekrekr** [comment] 2024-04-04 10:01
Closing as duplicate of https://github.com/dataform-co/dataform/issues/1509

**Closed** 2024-04-04 10:02 UTC
Labels: bug
